Multi file upload
jaydenseric/apollo-upload-examples pull request #1
Opened 2017-04-04 03:13 UTC by michaelmerrill

Hey Jay,

I started working on the multiple file component. It's a wip, but I thought I'd check in and see if this is the direction you were thinking? I used rethinkdb as a dummy db since it's been fairly popular with the graphql community lately, but I'm happy to change it.

2017-04-04 03:43 UTC, jaydenseric requested changes
Awesome work!!! 🙌

2017-04-04 03:43 UTC, jaydenseric commented on api/schema.graphql
> +  multiUpload (files: [Upload!]): [File!]
It should be `[Upload!]!` and `[File!]!` to indicate the array itself, as well as the inner items are required.

2017-04-04 03:43 UTC, jaydenseric commented on client/components/multi-uploader.js
> +  mutation multiUpload ($files: [Upload!]) {
Same here: `[Upload!]!`.

2017-04-04 03:43 UTC, jaydenseric commented on api/config.js
> +export const rethinkdb = {
Lets populate these from the `.env` file, and add these suggested values to `.env.example`.

2017-04-04 03:43 UTC, jaydenseric commented on api/resolvers.js
> +      return await db.table('uploads')
Pretty sure Apollo can handle promises and the `await` is not necessary.

2017-04-04 03:43 UTC, jaydenseric commented on api/rethinkdb.js
> +import {rethinkdb} from './config'
Perhaps skip config for this, and use the new .env entries directly in this file.

2017-04-04 03:43 UTC, jaydenseric commented on app/pages/index.js
> +          height: calc(50vh - 4em);
Not sure why there is a fixed height, and with a calc? You can do something like `padding-top: 3em;` to create responsive spacing between sections.

2017-04-04 03:43 UTC, jaydenseric commented on app/pages/index.js
> +      <h1>Apollo upload example (single file)</h1>
Lets have a h1 `Apollo upload examples` above the sections, and simplify the text of the section headings and make them h2.

2017-04-04 18:10 UTC, michaelmerrill commented
Sweet, thanks for the changes. I also added the list component and I'm now getting the `window is undefined` error. Also, did you want to show the images from the /tmp folder? I wasn't quite sure how to do that so instead I just have the names listed.

2017-04-05 00:47 UTC, jaydenseric commented
Just the names listed will be fine for now. And great chicken-or-the egg question about the error! Perhaps I will use your WIP, fix that error, and then we merge.

2017-04-05 03:32 UTC, jaydenseric commented
Need to add the DB stuff to `.env.example`.

2017-04-05 03:41 UTC, jaydenseric commented
I think I have solved all the issues with `apollo-upload-server` and `apollo-upload-client`, but I can't get your fork to work to test it.

I'm getting a lot of `Fail to create a new connection for the connection pool.` errors. Does RethinkDB have to be globally setup or something? If so, we will need to look at a different lightweight DB that does not require any global setup.

2017-04-05 03:44 UTC, jaydenseric commented
Quick Google:

- https://github.com/typicode/lowdb
- https://www.npmjs.com/package/diskdb

2017-04-05 05:35 UTC, michaelmerrill commented
You're right, rethink requires a global setup. Oops! I swapped it out with lowdb. I also updated the apollo-upload-client & server and everything seems to be working. Thank you!

2017-04-06 00:57 UTC, jaydenseric commented on api/db.json
> +{"uploads":[{"name":"IMG_0599.JPG","type":"image/jpeg","size":343845,"path":"/tmp/uploads/upload_7b8d12d21774c726904d6272f6176d57"},{"name":"IMG_0599.JPG","type":"image/jpeg","size":343845,"path":"/t
Need to add this file to the gitignore, and remove what was already committed here.

2017-04-06 14:23 UTC, jaydenseric approved these changes

2017-04-06 14:23 UTC, jaydenseric commented
Ok to merge?

2017-04-06 14:43 UTC, michaelmerrill commented
Yep! Changes made and it's gtg! Thanks, this has been fun. Really liked working with your code base 👍

2017-04-06 14:48 UTC, merged

2017-04-06 14:49 UTC, jaydenseric commented
Thanks for the help :)